# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load environment variables
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env

      - name: Check environment variables
        run: cat .env

      - name: create Downloads folder
        run: mkdir -p /home/runner/Downloads

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Install Playwright browsers (with deps)
        run: go run github.com/playwright-community/playwright-go/cmd/playwright@v0.5101.0 install --with-deps --only-shell

      - name: Build
        run: go build -v ./browser-use/...

      - name: Test
        run: go test -v ./browser-use/...
